name: invenbill
description: A smart inventory & billing system for small business, built with Flutter and Laravel backend.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  mobile_scanner: ^3.2.0
  pdf: ^3.10.7
  printing: ^5.12.0
  fl_chart: ^0.66.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  image_picker: ^1.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png